openapi: 3.1.0
servers:
  - url: //staging-manabie.my.salesforce.com/
    description: Sandbox server
info:
  version: 0.1.1
  title: Manabie API Documentation
  termsOfService: http://swagger.io/terms/
    <SecurityDefinitions />
  x-logo:
    url: 'https://backoffice.staging.manabie.io/images/manabie.png'
    altText: Manabie logo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
    identifier: Apache 2.0
tags:
  - name: Authentication
    description: >
      Salesforce API uses OAuth 2.0 Client Credentials Flow for Server-to-Server integration.
      This authentication method is designed for server-to-server scenarios, bypassing user interaction.
      It allows a client application to directly authenticate to the Salesforce server using its client ID and client secret.
      <br />
      <br />
      The client application first sends its client ID and client secret in a request to the Salesforce server.
      The server verifies the client credentials and issues an access token to the client application.
      The client application can then use the access token to authenticate to the Salesforce server on behalf of the application itself.
      <br />
      <br />
      For generating the access token using Client Credentials Flow, please refer to the [Salesforce
      documentation](https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_client_credentials_flow.htm&type=5)
      for the full implementation.
  - name: Error Codes
    description: >-
      This section provides a list of error codes that may be returned by the API.
      Each error code is accompanied by a description of the error and possible solutions.
  - name: Location
    description: >-
      This section pertains to all APIs related to your location data. It may
      include APIs for creating, retrieving, updating, and deleting location
      objects, as well as APIs for querying location data based on specific
      criteria. Each location object may contain details such as coordinates,
      address, and other relevant geographical information.
  - name: Package
    description: Information about a product package within an academic year.
  - name: Course
    description: |
      This section pertains to all APIs related to your course data. It may
      include APIs for creating, retrieving, updating, and deleting course
      objects, as well as APIs for querying course data based on specific
      criteria. Each course object may contain details such as course name,
      description, and other relevant information.
  - name: Order
    description: |
      This section pertains to all APIs related to your order data. It may
      include APIs for creating, retrieving, updating, and deleting order
      objects, as well as APIs for querying order data based on specific
      criteria. Each order object may contain details such as order number,
      date, and other relevant information.
  - name: Invoice
    description: |
      This section pertains to all APIs related to your invoice data. It may
      include APIs for creating, retrieving, updating, and deleting invoice
      objects, as well as APIs for querying invoice data based on specific
      criteria. Each invoice object may contain details such as invoice number,
      date, and other relevant information.
  - name: User
    description: |
      This section pertains to all APIs related to your user data. It may
      include APIs for creating, retrieving, updating, and deleting user
      objects, as well as APIs for querying user data based on specific
      criteria. Each user object may contain details such as name, email,
      and other relevant information.
  - name: Timesheet
    description: |
      This section pertains to all APIs related to your timesheet data. It may
      include APIs for creating, retrieving, updating, and deleting timesheet
      objects, as well as APIs for querying timesheet data based on specific
      criteria. Each timesheet object may contain details such as date, time,
      and other relevant information.
  - name: Webhooks
    description: Everything about your Webhooks
  - name: CourseModel
    x-displayName: Course
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Course" />
  - name: LocationModel
    x-displayName: Location
    description: >
      <SchemaDefinition schemaRef="#/components/schemas/Location" />
  - name: StudentModel
    x-displayName: Student
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/MANAERP_Student" />
  - name: StaffModel
    x-displayName: Staff
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/MANAERP_Staff" />
x-tagGroups:
  - name: General
    tags:
      - Authentication
      - Webhooks
  - name: Master Data API
    tags:
      - Location
      - Package
      - Course
  - name: User Management
    tags:
      - User
  - name: Invoice & Order Management
    tags:
      - Order
      - Invoice
  - name: Timesheet Management
    tags:
      - Timesheet
  - name: Models
    tags:
      - CourseModel
      - LocationModel
      - StudentModel
      - StaffModel
security:
  - {}
paths:
  /services/oauth2/token?grant_type=client_credentials&client_id={Client_ID}&client_secret={Client_Secret}:
    $ref: paths/auth/services_oauth2_token.yaml
  /services/apexrest/Location/getList?limit={limit}&cursor={next_cursor}:
    $ref: paths/master/location.yaml
  /services/apexrest/Location/:id:
    $ref: paths/master/location_{location_id}.yaml
  /services/apexrest/Package/getList?limit={limit}&cursor={next_cursor}:
    $ref: paths/master/package.yaml
  /services/apexrest/Package/:id:
    $ref: paths/master/package_{package_id}.yaml
  /services/apexrest/Course/getList?limit={limit}&cursor={next_cursor}:
    $ref: paths/master/course.yaml
  /services/apexrest/Course/:id:
    $ref: paths/master/course_{course_id}.yaml
  /services/apexrest/StudentCourseSubscription/getList?limit={limit}&cursor={next_cursor}:
    $ref: paths/order/order.yaml
  /services/apexrest/StudentCourseSubscription/:id:
    $ref: paths/order/order_{findById}.yaml
  /services/apexrest/StudentCourseSubscription/updated/?start_date={start_date}&end_date={end_date}:
    $ref: paths/order/order_{findByDateRange}.yaml
  /services/data/v60.0/query/?q={Get_All_Student_Query}:
    $ref: paths/user/student.yaml
  /services/data/v60.0/query/?q={Find_Students_By_Ids_Query}:
    $ref: paths/user/student_{ids}.yaml
  /services/data/v60.0/query/?q={Get_All_Staff_Query}:
    $ref: paths/user/staff.yaml
  /services/data/v60.0/query/?q={Find_Staff_By_Ids_Query}:
    $ref: paths/user/staff_{ids}.yaml
  /services/apexrest/MANAERP/timesheet/v1/createTimesheetLessonEntries:
    $ref: paths/timesheet/timesheet_lesson_entry.yaml
